var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.getGlobal=function(f){return"undefined"!=typeof window&&window===f?f:"undefined"!=typeof global&&null!=global?global:f};$jscomp.global=$jscomp.getGlobal(this);$jscomp.checkEs6ConformanceViaProxy=function(){try{var f={},h=Object.create(new $jscomp.global.Proxy(f,{get:function(e,a,b){return e==f&&"q"==a&&b==h}}));return!0===h.q}catch(e){return!1}};$jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS=!1;
$jscomp.ES6_CONFORMANCE=$jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS&&$jscomp.checkEs6ConformanceViaProxy();$jscomp.arrayIteratorImpl=function(f){var h=0;return function(){return h<f.length?{done:!1,value:f[h++]}:{done:!0}}};$jscomp.arrayIterator=function(f){return{next:$jscomp.arrayIteratorImpl(f)}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(f,h,e){f!=Array.prototype&&f!=Object.prototype&&(f[h]=e.value)};$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.SymbolClass=function(f,h){this.$jscomp$symbol$id_=f;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:h})};
$jscomp.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};$jscomp.Symbol=function(){function f(e){if(this instanceof f)throw new TypeError("Symbol is not a constructor");return new $jscomp.SymbolClass($jscomp.SYMBOL_PREFIX+(e||"")+"_"+h++,e)}var h=0;return f}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var f=$jscomp.global.Symbol.iterator;f||(f=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[f]&&$jscomp.defineProperty(Array.prototype,f,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var f=$jscomp.global.Symbol.asyncIterator;f||(f=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("Symbol.asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(f){$jscomp.initSymbolIterator();f={next:f};f[$jscomp.global.Symbol.iterator]=function(){return this};return f};
$jscomp.makeIterator=function(f){var h="undefined"!=typeof Symbol&&Symbol.iterator&&f[Symbol.iterator];return h?h.call(f):$jscomp.arrayIterator(f)};$jscomp.owns=function(f,h){return Object.prototype.hasOwnProperty.call(f,h)};$jscomp.polyfill=function(f,h,e,a){if(h){e=$jscomp.global;f=f.split(".");for(a=0;a<f.length-1;a++){var b=f[a];b in e||(e[b]={});e=e[b]}f=f[f.length-1];a=e[f];h=h(a);h!=a&&null!=h&&$jscomp.defineProperty(e,f,{configurable:!0,writable:!0,value:h})}};
$jscomp.polyfill("WeakMap",function(f){function h(){if(!f||!Object.seal)return!1;try{var a=Object.seal({}),c=Object.seal({}),b=new f([[a,2],[c,3]]);if(2!=b.get(a)||3!=b.get(c))return!1;b.delete(a);b.set(c,4);return!b.has(a)&&4==b.get(c)}catch(p){return!1}}function e(){}function a(a){if(!$jscomp.owns(a,c)){var b=new e;$jscomp.defineProperty(a,c,{value:b})}}function b(c){var b=Object[c];b&&(Object[c]=function(c){if(c instanceof e)return c;a(c);return b(c)})}if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(f&&
$jscomp.ES6_CONFORMANCE)return f}else if(h())return f;var c="$jscomp_hidden_"+Math.random();b("freeze");b("preventExtensions");b("seal");var d=0,k=function(a){this.id_=(d+=Math.random()+1).toString();if(a){a=$jscomp.makeIterator(a);for(var c;!(c=a.next()).done;)c=c.value,this.set(c[0],c[1])}};k.prototype.set=function(b,d){a(b);if(!$jscomp.owns(b,c))throw Error("WeakMap key fail: "+b);b[c][this.id_]=d;return this};k.prototype.get=function(a){return $jscomp.owns(a,c)?a[c][this.id_]:void 0};k.prototype.has=
function(a){return $jscomp.owns(a,c)&&$jscomp.owns(a[c],this.id_)};k.prototype.delete=function(a){return $jscomp.owns(a,c)&&$jscomp.owns(a[c],this.id_)?delete a[c][this.id_]:!1};return k},"es6","es3");$jscomp.MapEntry=function(){};
$jscomp.polyfill("Map",function(f){function h(){if($jscomp.ASSUME_NO_NATIVE_MAP||!f||"function"!=typeof f||!f.prototype.entries||"function"!=typeof Object.seal)return!1;try{var a=Object.seal({x:4}),c=new f($jscomp.makeIterator([[a,"s"]]));if("s"!=c.get(a)||1!=c.size||c.get({x:4})||c.set({x:4},"t")!=c||2!=c.size)return!1;var b=c.entries(),d=b.next();if(d.done||d.value[0]!=a||"s"!=d.value[1])return!1;d=b.next();return d.done||4!=d.value[0].x||"t"!=d.value[1]||!b.next().done?!1:!0}catch(t){return!1}}
if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(f&&$jscomp.ES6_CONFORMANCE)return f}else if(h())return f;$jscomp.initSymbolIterator();var e=new WeakMap,a=function(a){this.data_={};this.head_=d();this.size=0;if(a){a=$jscomp.makeIterator(a);for(var c;!(c=a.next()).done;)c=c.value,this.set(c[0],c[1])}};a.prototype.set=function(a,c){a=0===a?0:a;var d=b(this,a);d.list||(d.list=this.data_[d.id]=[]);d.entry?d.entry.value=c:(d.entry={next:this.head_,previous:this.head_.previous,head:this.head_,key:a,
value:c},d.list.push(d.entry),this.head_.previous.next=d.entry,this.head_.previous=d.entry,this.size++);return this};a.prototype.delete=function(a){a=b(this,a);return a.entry&&a.list?(a.list.splice(a.index,1),a.list.length||delete this.data_[a.id],a.entry.previous.next=a.entry.next,a.entry.next.previous=a.entry.previous,a.entry.head=null,this.size--,!0):!1};a.prototype.clear=function(){this.data_={};this.head_=this.head_.previous=d();this.size=0};a.prototype.has=function(a){return!!b(this,a).entry};
a.prototype.get=function(a){return(a=b(this,a).entry)&&a.value};a.prototype.entries=function(){return c(this,function(a){return[a.key,a.value]})};a.prototype.keys=function(){return c(this,function(a){return a.key})};a.prototype.values=function(){return c(this,function(a){return a.value})};a.prototype.forEach=function(a,c){for(var b=this.entries(),d;!(d=b.next()).done;)d=d.value,a.call(c,d[1],d[0],this)};a.prototype[Symbol.iterator]=a.prototype.entries;var b=function(a,c){var b=c&&typeof c;"object"==
b||"function"==b?e.has(c)?b=e.get(c):(b=""+ ++k,e.set(c,b)):b="p_"+c;var d=a.data_[b];if(d&&$jscomp.owns(a.data_,b))for(a=0;a<d.length;a++){var g=d[a];if(c!==c&&g.key!==g.key||c===g.key)return{id:b,list:d,index:a,entry:g}}return{id:b,list:d,index:-1,entry:void 0}},c=function(a,c){var b=a.head_;return $jscomp.iteratorPrototype(function(){if(b){for(;b.head!=a.head_;)b=b.previous;for(;b.next!=b.head;)return b=b.next,{done:!1,value:c(b)};b=null}return{done:!0,value:void 0}})},d=function(){var a={};return a.previous=
a.next=a.head=a},k=0;return a},"es6","es3");$jscomp.polyfill("Array.from",function(f){return f?f:function(f,e,a){e=null!=e?e:function(a){return a};var b=[],c="undefined"!=typeof Symbol&&Symbol.iterator&&f[Symbol.iterator];if("function"==typeof c){f=c.call(f);for(var d=0;!(c=f.next()).done;)b.push(e.call(a,c.value,d++))}else for(c=f.length,d=0;d<c;d++)b.push(e.call(a,f[d],d));return b}},"es6","es3");
$jscomp.iteratorFromArray=function(f,h){$jscomp.initSymbolIterator();f instanceof String&&(f+="");var e=0,a={next:function(){if(e<f.length){var b=e++;return{value:h(b,f[b]),done:!1}}a.next=function(){return{done:!0,value:void 0}};return a.next()}};a[Symbol.iterator]=function(){return a};return a};$jscomp.polyfill("Array.prototype.keys",function(f){return f?f:function(){return $jscomp.iteratorFromArray(this,function(f){return f})}},"es6","es3");var $ci360;
(function(f){var h=function(){function e(){}e._keyStr="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789.-=";e.encode=function(a){for(var b="",c,d,k,g,f,h=0,p=e._utf8_encode(a);h<p.length;)c=p.charCodeAt(h++),a=p.charCodeAt(h++),d=p.charCodeAt(h++),k=c>>2,c=(c&3)<<4|a>>4,g=(a&15)<<2|d>>6,f=d&63,isNaN(a)?g=f=64:isNaN(d)&&(f=64),b=b+e._keyStr.charAt(k)+e._keyStr.charAt(c)+e._keyStr.charAt(g)+e._keyStr.charAt(f);return b};e._utf8_encode=function(a){a=a.replace(/\r\n/g,"\n");for(var b="",
c=0;c<a.length;c++){var d=a.charCodeAt(c);128>d?b+=String.fromCharCode(d):(127<d&&2048>d?b+=String.fromCharCode(d>>6|192):(b+=String.fromCharCode(d>>12|224),b+=String.fromCharCode(d>>6&63|128)),b+=String.fromCharCode(d&63|128))}return b};return e}();f.Base64=h})($ci360||($ci360={}));
(function(f){var h=function(){function e(a,b,c,d,k){this.clientBaseTimestamp=(new Date).getTime();this.RETRIEVE_DATAHUB_ID_TIMEOUT=1500;this.configService=a;this.persistenceService=b;this.networkService=c;this.paramService=d;this.spotService=k}e.prototype.send=function(a,b){var c=this;void 0===b&&(b=!0);this.persistenceService.registerActivity();var d;a.hasOwnProperty("eventName")&&(d=a.eventName);var k=new f.CI360EventObj(d,Date.now());this.addFieldsToEvent(k,a);this.decorateEvent(k);a=this.paramService.validateEvent(k);
"success"===a&&(this.paramService.obfuscateFields(k),k.paramMap.delete("obfuscateFields"),this.paramService.mapTransportNames(k),this.sendEvent(k,b),"identity"==d&&setTimeout(function(){return c.configService.retrieveDid()},this.RETRIEVE_DATAHUB_ID_TIMEOUT));return a};e.prototype.addFieldsToEvent=function(a,b){"submit"===a.paramMap.get("eventName")&&this.paramService.submitEventHandling(a,b);"change"===a.paramMap.get("eventName")&&this.paramService.changeEventHandling(a,b);"cart"===a.paramMap.get("eventName")&&
this.paramService.cartEventHandling(a,b);"load"===a.paramMap.get("eventName")&&this.networkService.setCachedLoadEvent(a);for(var c in b)b.hasOwnProperty(c)&&"items"!==c&&a.paramMap.set(c,b[c])};e.prototype.sendEvent=function(a,b){b&&a.paramMap.set("initiator","api");a.paramMap.set("event_guid",this.networkService.getRandomGuid());"impression_viewable"===a.paramMap.get("eventName")?a.paramMap.set("event","spot_viewable"):a.paramMap.set("event",a.paramMap.get("eventName"));a.paramMap.set("eventname",
a.paramMap.get("eventName"));this.networkService.pushEvent(a)};e.prototype.decorateEvent=function(a){var b=this.configService.getConfig(),c=parseInt(b.timestamp,10),d=parseInt(a.paramMap.get("cts"));a.paramMap.set("timestamp",(c+d-this.clientBaseTimestamp).toString());a.paramMap.set("cts",d.toString());a.paramMap.set("tab_id",this.persistenceService.getTabId());c={ccs:"ccs",csu:"csu",datahubId:"datahub_id",vid:"visitor"};for(var k in c)a.paramMap.set(c[k],b[k]);this.spotService.decorateEvent(a);this.paramService.addDefaultFields(a)};
return e}();f.EventService=h})($ci360||($ci360={}));
(function(f){var h=function(){function e(){this.readyCallbacks=[];this.isReady=!1;this.initError=null;this.initStarted=!1;this.services=[];this.efname="ci360";this.lazyInit=!1}e.prototype.updateExposedFunction=function(){var a=this,b=this.ef&&this.ef.q,c=window[this.efname]=function(){for(var c=[],b=0;b<arguments.length;b++)c[b]=arguments[b];return a.api[c[0]]?a.api[c[0]](c[1],c[2]):"Not able to perform "+c[0]+" on ci360()"};if(b){for(var d=0;d<b.length;d++)c.apply(void 0,b[d]);b.length=0}};e.prototype.notifyReady=
function(){this.isReady=!0;for(var a=0,b=this.readyCallbacks;a<b.length;a++)(0,b[a])(this.initError);this.readyCallbacks.length=0};e.prototype.notifyError=function(a){this.initError=a;this.notifyReady()};e.prototype.addReadyCallback=function(a){this.isReady?a(this.initError):this.readyCallbacks.push(a)};e.prototype.done=function(a){var b=this;null==a?0<this.services.length?this.services.shift().init(function(a){return b.done(a)}):this.notifyReady():this.notifyError(a)};e.prototype.require=function(){for(var a=
[],b=0;b<arguments.length;b++)a[b]=arguments[b];if(!this.initStarted&&a)for(b=0;b<a.length;b++)this.services.push(a[b])};e.prototype.initialize=function(){this.initStarted||this.lazyInit||(this.initStarted=!0,this.done())};e.prototype.createApi=function(a,b,c,d){var k=this;this.api={ready:function(a){k.addReadyCallback(a)},send:function(a){return c.send(a)},detachIdentity:function(){return a.detachIdentity()},attachIdentity:function(c){return a.attachIdentity(c)},info:function(){var c={},d=a.getConfig();
c.datahubId=a.getDatahubId();c.vid=d.vid;c.sid=d.sid;f.exposeParamsMetadata=!0;f.exposeParamsMetadata&&(c.params_metadata=b.getParamsMetadata());return c},getCreatives:function(a,c){return d.getCreatives(a,c)},getPersonalizedCreative:function(a,c){return d.getPersonalizedCreative(a,c)},getSpotDefinitions:function(a,c){return d.getSpotDefinitions(a,c)},init:function(){k.initialize()}}};e.prototype.getEnvironmentAttributes=function(){var a=this;if(null==this.envAttrs){this.envAttrs={};var b=document.getElementById("ob-script-async");
if(null!=b){this.efname=b.dataset.efname||this.efname;var c=(this.ef=window[this.efname])&&this.ef.a&&JSON.parse(JSON.stringify(this.ef.a))||{},d=b.getAttribute("src"),k=document.createElement("a");k.href=d;this.envAttrs.protocol=k.protocol;this.envAttrs.hostname=k.hostname;this.envAttrs.port=k.port;this.envAttrs.extTenantId=c.tenantId&&c.tenantId.trim()||b.getAttribute("a")&&b.getAttribute("a").trim();this.envAttrs.hiddenClass=c.hiddenClass;this.envAttrs.defaultDomain=c.defaultDomain;c.identity&&
(this.envAttrs.identityType=c.identity.type,this.envAttrs.identitySource=c.identity.source||"cookie",this.envAttrs.identityName=c.identity.name,this.envAttrs.identityObscure=c.identity.obscure||!1);this.readyCallbacks.push(function(){return a.updateExposedFunction()})}else console.log("tag not found, environment is not ready")}return this.envAttrs};e.prototype.setLazyInit=function(a){void 0===a&&(a=!1);if(this.lazyInit=a){var b=this;this.ef&&this.ef.q&&Object.defineProperty(this.ef.q,"push",{enumerable:!1,
configurable:!1,writable:!1,value:function(a){0<a.length&&"init"===a[0]?(b.lazyInit=!1,b.initialize()):this[this.length]=a;return this.length}})}};return e}();f.Bootstrap=h})($ci360||($ci360={}));
(function(f){var h=function(){function e(a,b){this.paramMap=new Map;this.obscureCount=0;null!=a&&this.paramMap.set("eventName",a);null!=b&&this.paramMap.set("cts",b.toString())}e.prototype.populate=function(a){a=JSON.parse(a);for(var b in a)this.paramMap.set(b,a[b])};e.prototype.toJSONString=function(){return JSON.stringify(this)};e.prototype.toJSON=function(){var a={};this.paramMap.forEach(function(b,c){a[c]=b});return a};e.prototype.toURLEncoded=function(){var a="";this.paramMap.forEach(function(b,
c){a+=encodeURIComponent(c)+"="+encodeURIComponent(b)+"&"});return a.slice(0,a.length-1)};return e}();f.CI360EventObj=h})($ci360||($ci360={}));
(function(f){var h=function(){function e(a,b,c,d,k){var g=this;this.serverInfo={protocol:"",hostname:"",port:""};this.config={vid:"",sid:"",timestamp:"",isNewVid:!1,isNewSid:!1,datahubId:"",loadId:"",ccs:"",csu:"",sdu:"",sld:"",collect:{},jsVarsToObserve:[],contentChangeSelectors:[],cart:{},conf:{term:[],jsv:[]},formConfig:void 0,thresholds:void 0};this.updateNetworkService=!1;this.getExtTenantId=function(){return g.extTenantId};this.networkServiceObserver=function(){g.updateNetworkService=!0;g.networkService.call(g.buildConfigURL(!0),
g.configLoadCallback)};this.handleConfig=function(a){g.config.sid=a.sid||"";g.config.vid=a.vid||"";g.config.timestamp=a.timestamp||"";g.config.isNewSid=a.isNewSid||!1;g.config.isNewVid=a.isNewVid||!1;g.config.datahubId=a.datahubId||"";g.config.loadId=a.loadId||"";g.config.collect=a.collect||{};g.config.csu=a.csu||"";g.config.sld=a.sld||"";g.config.conf=a.conf||{term:[],jsv:[]};g.config.jsVarsToObserve=a.jsVarsToObserve||[];g.config.contentChangeSelectors=a.contentChangeSelectors||[];g.config.cart=
a.cart||{};g.config.formConfig=a.formConfig;g.persistenceService.setSld(g.config.sld);g.networkService.setLoadId(g.config.loadId);g.networkService.setSessionId(g.config.sid);g.config.thresholds=a.thresholds};this.setCookies=function(a){g.persistenceService.setVid(a.vid);g.persistenceService.setSid(a.sid);g.persistenceService.setDid(a.datahubId)};this.configLoadCallback=function(a){a=JSON.parse(a);g.handleConfig(a);g.setCookies(a);g.updateNetworkService&&(g.updateNetworkService=!1,g.networkService.processEvents(!1))};
this.buildIdentity=function(a){var c=new f.CI360EventObj("identity"),b=g.getConfig(),d="Unable to populate loginId.",l=g.getConfig().timestamp||(new Date).getTime();c.paramMap.set("timestamp",l.toString());c.paramMap.set("tab_id",g.persistenceService.getTabId());c.paramMap.set("hb",g.persistenceService.getSidArray()[2]);l={loadId:"load_id",sid:"session",vid:"visitor"};for(var k in l)b[k]&&c.paramMap.set(l[k],b[k]);!a&&g.identityType&&g.identityName&&(a={url:function(){return g.util.extractParam(g.identityName,
window.location.href)},jsvar:function(){return g.util.getJsVarValueSafe(g.identityName)},"default":function(){return g.persistenceService.getCookie(g.identityName)}},a={loginEventType:g.identityType,loginId:(a[g.identitySource]||a["default"])(),obfuscateFields:"["+(g.identityObscure&&'"loginId"'||'""')+"]"});return a&&a.loginId&&(g.paramService.addFieldsToEvent(c,a),"success"===(d=g.paramService.validateEvent(c)))?(g.paramService.obfuscateFields(c),g.paramService.mapTransportNames(c),c.paramMap.delete("eventName"),
[c.toURLEncoded(),d]):[null,d]};this.retrieveDid=function(){g.networkService.call(g.buildDatahubURL(),g.updateDid)};this.updateDid=function(a){null!=a&&/^([0-9]|[a-z]|[A-Z]|-){24,256}$/.test(a)&&(g.persistenceService.setDid(a),g.config.datahubId=a)};this.getDatahubId=function(){return g.persistenceService.getDid()||g.config.datahubId};this.persistenceService=a;this.networkService=b;this.paramService=c;this.util=d;this.isOt2=k;this.networkService.addObserver(this.networkServiceObserver)}e.prototype.getThresholds=
function(){return this.config.thresholds?this.config.thresholds:[]};e.prototype.getFormConfig=function(){return this.config.formConfig};e.prototype.setEnvironmentAttributes=function(a){void 0===a&&(a={});this.serverInfo.protocol=a.protocol||"";this.serverInfo.hostname=a.hostname||"";this.serverInfo.port=a.port||"";this.extTenantId=a.extTenantId||"";this.networkService.setExtTenantId(this.extTenantId);this.paramService.setExtTenantId(this.extTenantId);this.persistenceService.setExtTenantId(this.extTenantId);
this.hiddenClass=a.hiddenClass||"";this.identityType=a.identityType||"";this.identityName=a.identityName||"";this.identitySource=a.identitySource||"";this.identityObscure=a.identityObscure||!1;this.networkService.setDefaultDomain(a.defaultDomain);this.config.ccs=this.serverInfo.protocol+"//"+this.serverInfo.hostname+":"+this.serverInfo.port+"/t/e/"+this.extTenantId;this.networkService.setCcs(this.config.ccs);this.config.sdu=this.serverInfo.protocol+"//"+this.serverInfo.hostname+":"+this.serverInfo.port+
"/t/s/p/"+this.extTenantId};e.prototype.buildConfigURL=function(a){void 0===a&&(a=!1);var b=this.serverInfo.protocol+"//"+this.serverInfo.hostname+":"+this.serverInfo.port+"/t/s/c/"+this.extTenantId,c="domain="+this.networkService.getDomain(),d=this.persistenceService.getVid();d=d?"&vid="+d:"";var k=this.persistenceService.getSidArray();k=k[0]?"&sid="+k[0]+"&hb="+k[2]:"";var g="";a||(g=(g=(g=window.com_sas_ci_acs)&&g.ob_configure&&g.ob_configure.getLoadId())?"&loadId="+g:"");var e=this.util.getUriInfo();
a="&p="+encodeURIComponent(e.path);var f="&params="+encodeURIComponent(e.search),p="&page_title="+encodeURIComponent(document.title),h="&referrer="+encodeURIComponent(document.referrer),l="&uri="+encodeURIComponent(document.URL),q=new Date,r="&cts="+q.getTime();q="&tzo="+q.getTimezoneOffset();var v="&platform="+navigator.platform,C="&port="+location.port;e="&protocol="+e.protocol;var w="&screen_info="+screen.width+"x"+screen.height+"@"+screen.colorDepth,n="&browser_language="+navigator.language,y=
"&character_set="+document.characterSet,F="&csz="+document.documentElement.outerHTML.length,K="&bsz="+window.innerWidth+"x"+window.innerHeight,z="&tab_id="+this.persistenceService.getTabId(),P="";this.isOt2&&(P="&init=ot2&version=2.1");return b+"?"+c+d+k+g+a+f+p+h+l+r+q+v+C+e+w+n+y+F+K+z+P};e.prototype.init=function(a){var b=this.buildIdentity()[0];this.networkService.call(this.buildConfigURL(),this.configLoadCallback,a,b&&"POST"||"GET",b)};e.prototype.getContentChangeInfo=function(){return this.config.contentChangeSelectors};
e.prototype.getIdentityInfo=function(){var a=window.hackConfig;if(null!=a&&null!=a.identityInfo)return a.identityInfo};e.prototype.getIdentityInfoLoad=function(){var a=window.hackConfig;if(null!=a&&null!=a.identityInfoLoad)return a.identityInfoLoad};e.prototype.getJsVarsToObserve=function(){return this.config.jsVarsToObserve};e.prototype.getFieldsToObscure=function(){var a=window.hackConfig;if(null!=a&&null!=a.obscureFields)return a.obscureFields};e.prototype.getCartConfiguration=function(){return this.config.cart};
e.prototype.attachIdentity=function(a){a=this.buildIdentity(a);a[0]&&this.networkService.call(this.buildDatahubURL(),this.updateDid,void 0,"POST",a[0]);return a[1]};e.prototype.detachIdentity=function(){this.networkService.call(this.buildDatahubURL(),this.updateDid,void 0,"DELETE")};e.prototype.buildDatahubURL=function(){return this.serverInfo.protocol+"//"+this.serverInfo.hostname+":"+this.serverInfo.port+"/t/s/d/"+this.extTenantId+"/"+this.getConfig().vid};e.prototype.getConfig=function(){this.config.datahubId=
this.persistenceService.getDid()||this.config.datahubId;return this.config};e.prototype.getPageElements=function(){return this.config.conf&&this.config.conf.term?this.config.conf.term:[]};e.prototype.getJsVars=function(){return this.config.conf&&this.config.conf.jsv?this.config.conf.jsv:[]};return e}();f.ConfigService=h})($ci360||($ci360={}));
(function(f){var h=function(){function e(){this.forge=this.initForge()}e.prototype.sha384=function(a){var b=this.forge.md.sha384.create();b.update(a);return b.digest().toHex()};e.prototype.initForge=function(){function a(a){if(8!==a&&16!==a&&24!==a&&32!==a)throw Error("Only 8, 16, 24, or 32 bits supported: "+a);}function b(a){this.data="";this.read=0;if("string"===typeof a)this.data=a;else if(a instanceof b||"object"===typeof a&&"string"===typeof a.data&&"number"===typeof a.read)this.data=a.data,
this.read=a.read;this._constructedStringLength=0}function c(a,c,b){for(var d,k,g,e,l,f,q,h,m,r,x,t,G,H,L,M,A,B,I,J,D,E,N,O,u,Q=b.length();128<=Q;){for(u=0;16>u;++u)c[u][0]=b.getInt32()>>>0,c[u][1]=b.getInt32()>>>0;for(;80>u;++u)l=c[u-2],m=l[0],l=l[1],d=((m>>>19|l<<13)^(l>>>29|m<<3)^m>>>6)>>>0,k=((m<<13|l>>>19)^(l<<3|m>>>29)^(m<<26|l>>>6))>>>0,l=c[u-15],m=l[0],l=l[1],g=((m>>>1|l<<31)^(m>>>8|l<<24)^m>>>7)>>>0,e=((m<<31|l>>>1)^(m<<24|l>>>8)^(m<<25|l>>>7))>>>0,m=c[u-7],r=c[u-16],l=k+m[1]+e+r[1],c[u][0]=
d+m[0]+g+r[0]+(l/4294967296>>>0)>>>0,c[u][1]=l>>>0;m=a[0][0];r=a[0][1];x=a[1][0];t=a[1][1];G=a[2][0];H=a[2][1];L=a[3][0];M=a[3][1];A=a[4][0];B=a[4][1];I=a[5][0];J=a[5][1];D=a[6][0];E=a[6][1];N=a[7][0];O=a[7][1];for(u=0;80>u;++u)d=((A>>>14|B<<18)^(A>>>18|B<<14)^(B>>>9|A<<23))>>>0,l=((A<<18|B>>>14)^(A<<14|B>>>18)^(B<<23|A>>>9))>>>0,k=(D^A&(I^D))>>>0,f=(E^B&(J^E))>>>0,g=((m>>>28|r<<4)^(r>>>2|m<<30)^(r>>>7|m<<25))>>>0,e=((m<<4|r>>>28)^(r<<30|m>>>2)^(r<<25|m>>>7))>>>0,q=(m&x|G&(m^x))>>>0,h=(r&t|H&(r^t))>>>
0,l=O+l+f+p[u][1]+c[u][1],d=N+d+k+p[u][0]+c[u][0]+(l/4294967296>>>0)>>>0,k=l>>>0,l=e+h,g=g+q+(l/4294967296>>>0)>>>0,e=l>>>0,N=D,O=E,D=I,E=J,I=A,J=B,l=M+k,A=L+d+(l/4294967296>>>0)>>>0,B=l>>>0,L=G,M=H,G=x,H=t,x=m,t=r,l=k+e,m=d+g+(l/4294967296>>>0)>>>0,r=l>>>0;l=a[0][1]+r;a[0][0]=a[0][0]+m+(l/4294967296>>>0)>>>0;a[0][1]=l>>>0;l=a[1][1]+t;a[1][0]=a[1][0]+x+(l/4294967296>>>0)>>>0;a[1][1]=l>>>0;l=a[2][1]+H;a[2][0]=a[2][0]+G+(l/4294967296>>>0)>>>0;a[2][1]=l>>>0;l=a[3][1]+M;a[3][0]=a[3][0]+L+(l/4294967296>>>
0)>>>0;a[3][1]=l>>>0;l=a[4][1]+B;a[4][0]=a[4][0]+A+(l/4294967296>>>0)>>>0;a[4][1]=l>>>0;l=a[5][1]+J;a[5][0]=a[5][0]+I+(l/4294967296>>>0)>>>0;a[5][1]=l>>>0;l=a[6][1]+E;a[6][0]=a[6][0]+D+(l/4294967296>>>0)>>>0;a[6][1]=l>>>0;l=a[7][1]+O;a[7][0]=a[7][0]+N+(l/4294967296>>>0)>>>0;a[7][1]=l>>>0;Q-=128}}var d=d||{};d.md=d.md||{};d.md.algorithms=d.md.algorithms||{};var k=d.sha512=d.sha512||{};d.util=d.util||{};d.util.fillString=function(a,c){for(var b="";0<c;)c&1&&(b+=a),c>>>=1,0<c&&(a+=a);return b};d.util.createBuffer=
function(a,c){void 0!==a&&"utf8"===(c||"raw")&&(a=d.util.encodeUtf8(a));return new d.util.ByteBuffer(a)};d.util.encodeUtf8=function(a){return unescape(encodeURIComponent(a))};d.util.ByteBuffer=b;d.util.isArrayBuffer=function(a){return"undefined"!==typeof ArrayBuffer&&a instanceof ArrayBuffer};d.util.isArrayBufferView=function(a){return a&&d.util.isArrayBuffer(a.buffer)&&void 0!==a.byteLength};d.util.ByteStringBuffer=b;d.util.ByteStringBuffer.prototype._optimizeConstructedString=function(a){this._constructedStringLength+=
a;4096<this._constructedStringLength&&(this.data.substr(0,1),this._constructedStringLength=0)};d.util.ByteStringBuffer.prototype.length=function(){return this.data.length-this.read};d.util.ByteStringBuffer.prototype.isEmpty=function(){return 0>=this.length()};d.util.ByteStringBuffer.prototype.putByte=function(a){return this.putBytes(String.fromCharCode(a))};d.util.ByteStringBuffer.prototype.fillWithByte=function(a,c){a=String.fromCharCode(a);for(var b=this.data;0<c;)c&1&&(b+=a),c>>>=1,0<c&&(a+=a);
this.data=b;this._optimizeConstructedString(c);return this};d.util.ByteStringBuffer.prototype.putBytes=function(a){this.data+=a;this._optimizeConstructedString(a.length);return this};d.util.ByteStringBuffer.prototype.putString=function(a){return this.putBytes(d.util.encodeUtf8(a))};d.util.ByteStringBuffer.prototype.putInt16=function(a){return this.putBytes(String.fromCharCode(a>>8&255)+String.fromCharCode(a&255))};d.util.ByteStringBuffer.prototype.putInt24=function(a){return this.putBytes(String.fromCharCode(a>>
16&255)+String.fromCharCode(a>>8&255)+String.fromCharCode(a&255))};d.util.ByteStringBuffer.prototype.putInt32=function(a){return this.putBytes(String.fromCharCode(a>>24&255)+String.fromCharCode(a>>16&255)+String.fromCharCode(a>>8&255)+String.fromCharCode(a&255))};d.util.ByteStringBuffer.prototype.putInt16Le=function(a){return this.putBytes(String.fromCharCode(a&255)+String.fromCharCode(a>>8&255))};d.util.ByteStringBuffer.prototype.putInt24Le=function(a){return this.putBytes(String.fromCharCode(a&
255)+String.fromCharCode(a>>8&255)+String.fromCharCode(a>>16&255))};d.util.ByteStringBuffer.prototype.putInt32Le=function(a){return this.putBytes(String.fromCharCode(a&255)+String.fromCharCode(a>>8&255)+String.fromCharCode(a>>16&255)+String.fromCharCode(a>>24&255))};d.util.ByteStringBuffer.prototype.putInt=function(c,b){a(b);var d="";do b-=8,d+=String.fromCharCode(c>>b&255);while(0<b);return this.putBytes(d)};d.util.ByteStringBuffer.prototype.putSignedInt=function(a,c){0>a&&(a+=2<<c-1);return this.putInt(a,
c)};d.util.ByteStringBuffer.prototype.putBuffer=function(a){return this.putBytes(a.getBytes())};d.util.ByteStringBuffer.prototype.getByte=function(){return this.data.charCodeAt(this.read++)};d.util.ByteStringBuffer.prototype.getInt16=function(){var a=this.data.charCodeAt(this.read)<<8^this.data.charCodeAt(this.read+1);this.read+=2;return a};d.util.ByteStringBuffer.prototype.getInt24=function(){var a=this.data.charCodeAt(this.read)<<16^this.data.charCodeAt(this.read+1)<<8^this.data.charCodeAt(this.read+
2);this.read+=3;return a};d.util.ByteStringBuffer.prototype.getInt32=function(){var a=this.data.charCodeAt(this.read)<<24^this.data.charCodeAt(this.read+1)<<16^this.data.charCodeAt(this.read+2)<<8^this.data.charCodeAt(this.read+3);this.read+=4;return a};d.util.ByteStringBuffer.prototype.getInt16Le=function(){var a=this.data.charCodeAt(this.read)^this.data.charCodeAt(this.read+1)<<8;this.read+=2;return a};d.util.ByteStringBuffer.prototype.getInt24Le=function(){var a=this.data.charCodeAt(this.read)^
this.data.charCodeAt(this.read+1)<<8^this.data.charCodeAt(this.read+2)<<16;this.read+=3;return a};d.util.ByteStringBuffer.prototype.getInt32Le=function(){var a=this.data.charCodeAt(this.read)^this.data.charCodeAt(this.read+1)<<8^this.data.charCodeAt(this.read+2)<<16^this.data.charCodeAt(this.read+3)<<24;this.read+=4;return a};d.util.ByteStringBuffer.prototype.getInt=function(c){a(c);var b=0;do b=(b<<8)+this.data.charCodeAt(this.read++),c-=8;while(0<c);return b};d.util.ByteStringBuffer.prototype.getSignedInt=
function(a){var c=this.getInt(a);a=2<<a-2;c>=a&&(c-=a<<1);return c};d.util.ByteStringBuffer.prototype.getBytes=function(a){if(a){a=Math.min(this.length(),a);var c=this.data.slice(this.read,this.read+a);this.read+=a}else 0===a?c="":(c=0===this.read?this.data:this.data.slice(this.read),this.clear());return c};d.util.ByteStringBuffer.prototype.bytes=function(a){return"undefined"===typeof a?this.data.slice(this.read):this.data.slice(this.read,this.read+a)};d.util.ByteStringBuffer.prototype.at=function(a){return this.data.charCodeAt(this.read+
a)};d.util.ByteStringBuffer.prototype.setAt=function(a,c){this.data=this.data.substr(0,this.read+a)+String.fromCharCode(c)+this.data.substr(this.read+a+1);return this};d.util.ByteStringBuffer.prototype.last=function(){return this.data.charCodeAt(this.data.length-1)};d.util.ByteStringBuffer.prototype.copy=function(){var a=d.util.createBuffer(this.data);a.read=this.read;return a};d.util.ByteStringBuffer.prototype.compact=function(){0<this.read&&(this.data=this.data.slice(this.read),this.read=0);return this};
d.util.ByteStringBuffer.prototype.clear=function(){this.data="";this.read=0;return this};d.util.ByteStringBuffer.prototype.truncate=function(a){a=Math.max(0,this.length()-a);this.data=this.data.substr(this.read,a);this.read=0;return this};d.util.ByteStringBuffer.prototype.toHex=function(){for(var a="",c=this.read;c<this.data.length;++c){var b=this.data.charCodeAt(c);16>b&&(a+="0");a+=b.toString(16)}return a};d.util.ByteStringBuffer.prototype.toString=function(){return d.util.decodeUtf8(this.bytes())};
d.md.sha512=d.md.algorithms.sha512=k;var g=d.sha384=d.sha512.sha384=d.sha512.sha384||{};g.create=function(){return k.create("SHA-384")};d.md.sha384=d.md.algorithms.sha384=g;d.sha512.sha256=d.sha512.sha256||{create:function(){return k.create("SHA-512/256")}};d.md["sha512/256"]=d.md.algorithms["sha512/256"]=d.sha512.sha256;d.sha512.sha224=d.sha512.sha224||{create:function(){return k.create("SHA-512/224")}};d.md["sha512/224"]=d.md.algorithms["sha512/224"]=d.sha512.sha224;k.create=function(a){f||(e=String.fromCharCode(128),
e+=d.util.fillString(String.fromCharCode(0),128),p=[[1116352408,3609767458],[1899447441,602891725],[3049323471,3964484399],[3921009573,2173295548],[961987163,4081628472],[1508970993,3053834265],[2453635748,2937671579],[2870763221,3664609560],[3624381080,2734883394],[310598401,1164996542],[607225278,1323610764],[1426881987,3590304994],[1925078388,4068182383],[2162078206,991336113],[2614888103,633803317],[3248222580,3479774868],[3835390401,2666613458],[4022224774,944711139],[264347078,2341262773],[604807628,
2007800933],[770255983,1495990901],[1249150122,1856431235],[1555081692,3175218132],[1996064986,2198950837],[2554220882,3999719339],[2821834349,766784016],[2952996808,2566594879],[3210313671,3203337956],[3336571891,1034457026],[3584528711,2466948901],[113926993,3758326383],[338241895,168717936],[666307205,1188179964],[773529912,1546045734],[1294757372,1522805485],[1396182291,2643833823],[1695183700,2343527390],[1986661051,1014477480],[2177026350,1206759142],[2456956037,344077627],[2730485921,1290863460],
[2820302411,3158454273],[3259730800,3505952657],[3345764771,106217008],[3516065817,3606008344],[3600352804,1432725776],[4094571909,1467031594],[275423344,851169720],[430227734,3100823752],[506948616,1363258195],[659060556,3750685593],[883997877,3785050280],[958139571,3318307427],[1322822218,3812723403],[1537002063,2003034995],[1747873779,3602036899],[1955562222,1575990012],[2024104815,1125592928],[2227730452,2716904306],[2361852424,442776044],[2428436474,593698344],[2756734187,3733110249],[3204031479,
2999351573],[3329325298,3815920427],[3391569614,3928383900],[3515267271,566280711],[3940187606,3454069534],[4118630271,4000239992],[116418474,1914138554],[174292421,2731055270],[289380356,3203993006],[460393269,320620315],[685471733,587496836],[852142971,1086792851],[1017036298,365543100],[1126000580,2618297676],[1288033470,3409855158],[1501505948,4234509866],[1607167915,987167468],[1816402316,1246189591]],h={"SHA-512":[[1779033703,4089235720],[3144134277,2227873595],[1013904242,4271175723],[2773480762,
1595750129],[1359893119,2917565137],[2600822924,725511199],[528734635,4215389547],[1541459225,327033209]],"SHA-384":[[3418070365,3238371032],[1654270250,914150663],[2438529370,812702999],[355462360,4144912697],[1731405415,4290775857],[2394180231,1750603025],[3675008525,1694076839],[1203062813,3204075428]],"SHA-512/256":[[573645204,4230739756],[2673172387,3360449730],[596883563,1867755857],[2520282905,1497426621],[2519219938,2827943907],[3193839141,1401305490],[721525244,746961066],[246885852,2177182882]],
"SHA-512/224":[[2352822216,424955298],[1944164710,2312950998],[502970286,855612546],[1738396948,1479516111],[258812777,2077511080],[2011393907,79989058],[1067287976,1780299464],[286451373,2446758561]]},f=!0);"undefined"===typeof a&&(a="SHA-512");if(!(a in h))throw Error("Invalid SHA-512 algorithm: "+a);for(var b=h[a],k=null,g=d.util.createBuffer(),l=Array(80),m=0;80>m;++m)l[m]=Array(2);m=64;switch(a){case "SHA-384":m=48;break;case "SHA-512/256":m=32;break;case "SHA-512/224":m=28}var n={algorithm:a.replace("-",
"").toLowerCase(),blockLength:128,digestLength:m,messageLength:0,fullMessageLength:null,messageLengthSize:16,messageLength128:null,update:null,digest:null,start:function(){n.messageLength=0;n.fullMessageLength=n.messageLength128=[];for(var a=n.messageLengthSize/4,c=0;c<a;++c)n.fullMessageLength.push(0);g=d.util.createBuffer();k=Array(b.length);for(c=0;c<b.length;++c)k[c]=b[c].slice(0);return n}};n.start();n.update=function(a,b){"utf8"===b&&(a=d.util.encodeUtf8(a));b=a.length;n.messageLength+=b;b=
[b/4294967296>>>0,b>>>0];for(var e=n.fullMessageLength.length-1;0<=e;--e)n.fullMessageLength[e]+=b[1],b[1]=b[0]+(n.fullMessageLength[e]/4294967296>>>0),n.fullMessageLength[e]>>>=0,b[0]=b[1]/4294967296>>>0;g.putBytes(a);c(k,l,g);(2048<g.read||0===g.length())&&g.compact();return n};n.digest=function(){var b=d.util.createBuffer();b.putBytes(g.bytes());b.putBytes(e.substr(0,n.blockLength-(n.fullMessageLength[n.fullMessageLength.length-1]+n.messageLengthSize&n.blockLength-1)));for(var f,m,p=8*n.fullMessageLength[0],
h=0;h<n.fullMessageLength.length-1;++h)f=8*n.fullMessageLength[h+1],m=f/4294967296>>>0,p+=m,b.putInt32(p>>>0),p=f>>>0;b.putInt32(p);f=Array(k.length);for(h=0;h<k.length;++h)f[h]=k[h].slice(0);c(f,l,b);b=d.util.createBuffer();m="SHA-512"===a?f.length:"SHA-384"===a?f.length-2:f.length-4;for(h=0;h<m;++h)b.putInt32(f[h][0]),h===m-1&&"SHA-512/224"===a||b.putInt32(f[h][1]);return b};return n};var e=null,f=!1,p=null,h=null;return d};return e}();f.EncodingService=h})($ci360||($ci360={}));
(function(f){var h=function(){function e(a,b){var c=this;this.setExtTenantId=function(a){c.key+=a};this.DELIMITER=String.fromCharCode(127);this.size=0;this.key=a;this.storageType=b}e.prototype.storage=function(){return f[this.storageType]};e.prototype.retrieveItem=function(a){a=a?a:this.key;var b=this.storage().getItem(a);return b&&null!=b?b:(this.storage().setItem(a,""),"")};e.prototype.push2Front=function(a){try{var b=a.toJSONString(),c=this.retrieveItem(this.key);c=""==c?b:b+this.DELIMITER+c;this.storage().setItem(this.key,
c);this.size++}catch(d){return!1}return!0};e.prototype.push=function(a){try{var b=a.toJSONString(),c=this.retrieveItem(this.key);c+=""==c?b:this.DELIMITER+b;this.storage().setItem(this.key,c);this.size++}catch(d){return!1}return!0};e.prototype.pop=function(a){void 0===a&&(a=!1);try{var b=this.retrieveItem(this.key),c=b.indexOf(this.DELIMITER);if(-1<c){var d=b.substr(0,c);b=b.substr(c+1);this.storage().setItem(this.key,b);this.size--;if(a){var k=new f.CI360EventObj;k.populate(d);return k}}else if(0<
b.length&&(this.storage().setItem(this.key,""),this.size=0,a))return k=new f.CI360EventObj,k.populate(b),k;return null}catch(g){return null}};e.prototype.getFront=function(){try{var a=this.retrieveItem(this.key),b=a.indexOf(this.DELIMITER);if(-1<b){var c=a.substr(0,b),d=new f.CI360EventObj;d.populate(c);return d}return 0<a.length?(d=new f.CI360EventObj,d.populate(a),d):null}catch(k){return null}};return e}();f.LocalQueue=h})($ci360||($ci360={}));
(function(f){var h=function(){function e(a,b){var c=this;this.maxResendCount=3;this.resendCount=0;this.sendLock=!1;this.intialTimeout=1500;this.bodyInHeaderLoad=this.bodyInHeaderAll=!1;this.com_sas_ci_acs=window.com_sas_ci_acs;this.legacyTagLoaded=!1;this.firstLoad=!0;this.setLoadId=function(a){c.loadId=a;c.legacyTagLoaded&&(c.com_sas_ci_acs.ob_configure.getLoadId=function(){return a})};this.setDefaultDomain=function(a){c.defaultDomain=a};this.getDomain=function(){return document.domain||c.defaultDomain||
""};this.getRandomGuid=function(){return c.loadId+Math.floor(1E12*Math.random()+1)};this.setSessionId=function(a){c.sessionId=a};this.observers=[];this.setExtTenantId=function(a){c.q.setExtTenantId(a)};this.setCcs=function(a){c.ccs=a};this.unlocked=function(){return!1===c.sendLock};this.call=function(a,c,b,e,f){void 0===c&&(c=function(){});void 0===b&&(b=function(){});void 0===e&&(e="GET");var d=new XMLHttpRequest;d.onreadystatechange=function(){d.readyState===XMLHttpRequest.DONE&&200<=d.status&&
300>d.status?d.responseText?(c(d.responseText),b()):b(Error("Response is Empty.")):d.readyState===XMLHttpRequest.DONE&&503===d.status&&b(Error("(503) Service is not available."))};d.withCredentials=!0;d.open(e,a);f&&d.setRequestHeader("Content-Type","application/x-www-form-urlencoded;");d.send(f||null)};this.resendEvent=function(){setTimeout(function(){c.resendCount<c.maxResendCount?c.resendCount++:(c.q.pop(!1),c.resendCount=0);c.processEvents(!1)},1E3*(c.resendCount+1))};this.sendEvent=function(a){c.ccs&&
c.send(c.ccs,a.toURLEncoded(),"POST",c.eventResponseHandler,null)};this.processEvents=function(a){c.isReal(a)&&(c.sendLock=a);a=null;c.unlocked()&&(a=c.q.getFront())&&(c.sendLock=!0,c.sendEvent(a))};this.pushEvent=function(a){c.q.push(a);c.unlocked()&&c.processEvents()};this.send=function(a,b,e,f,h){var d=void 0;try{var g=c.intialTimeout*(c.resendCount+1);d=new XMLHttpRequest;d.onreadystatechange=function(){f(d,h)};"function"===typeof d.onloadend&&(d.onloadend=function(){c.cancelTimer(d)});if("POST"==
e)d.open(e,a,!0),d.timeout=g,d.setRequestHeader("Content-Type","application/x-www-form-urlencoded;charset=UTF-8"),(c.bodyInHeaderAll||c.bodyInHeaderLoad&&b&&-1<b.indexOf("event=load"))&&d.setRequestHeader("X-SI-EventBody",b),d.onloadstart=function(){d.ontimeout=function(){c.timeout(d)}};else{var k=null!=b?a.indexOf("?")?"&"+b:"?"+b:"";d.open(e,a+k,!0)}d.withCredentials=!0;b+="&sndcts="+Date.now()+"&session="+c.sessionId+"&hb="+c.persistenceService.getSidArray()[2];var m=-1<b.indexOf("eventName=load");
!c.firstLoad&&m||(b+="&load_id="+c.loadId);c.firstLoad&&m&&(c.firstLoad=!1);b+="&domain="+c.getDomain();d.send(b)}catch(r){d&&d.abort(),c.resendEvent()}};this.cancelTimer=function(a){a.timeout&&clearTimeout(a.timeout);a.ontimeout=null};this.eventResponseHandler=function(a){if(c.isReal(a.readyState)&&a.readyState==XMLHttpRequest.DONE)if(c.cancelTimer(a),200<=a.status&&300>a.status){if(-1<a.responseText.indexOf("load_id")){var b=void 0;try{b=JSON.parse(a.responseText),b.load_id&&c.setLoadId(b.load_id)}catch(g){}}else if(-1<
a.responseText.indexOf("sid")){c.firstLoad=!0;c.cachedLoadEvent&&-1==a.responseText.indexOf("load")&&(c.cachedLoadEvent.paramMap.set("event_guid",c.getRandomGuid()),c.q.push2Front(c.cachedLoadEvent));c.notifyObservers();return}c.q.pop(!1);c.resendCount=0;c.processEvents(!1)}else a.abort(),c.resendEvent()};this.timeout=function(a,b){void 0===b&&(b=!0);a&&a.abort();b&&c.resendEvent()};this.q=a;this.persistenceService=b;(this.legacyTagLoaded=this.com_sas_ci_acs&&this.com_sas_ci_acs.ob_configure)&&this.com_sas_ci_acs.ob_configure.getLoadId()&&
(this.firstLoad=!1)}e.prototype.addObserver=function(a){this.observers.push(a)};e.prototype.setCachedLoadEvent=function(a){this.cachedLoadEvent=a};e.prototype.notifyObservers=function(){for(var a=0,b=this.observers;a<b.length;a++)(0,b[a])()};e.prototype.isReal=function(a){return"undefined"!=typeof a||null!=a};return e}();f.NetworkService=h})($ci360||($ci360={}));
(function(f){var h=function(){function e(a){var b=this;this.setExtTenantId=function(a){b.extTenantId=a};this.REGULAR_EXPRESSIONS={INTEGER:"^[\\-]?\\d+$",DECIMAL:"^[0-9]+(.[0-9]{1,2})?$"};this.SPOT_DEP_EVENTS={clickthrough:"1",impression:"1",impressionViewable:"1"};this.SPOT_DEP_EVENT_KEYS={creativeId:"1",spotId:"1",taskId:"1"};this.PARAMS_METADATA={cart:{action:{required:!0,regex:"^cartview$|^checkout$|^purchase$",internal_name:"cart_type"},uri:{required:!0,default_value:function(){return document.URL}},
id:{types:["string","number"],required:!0,regex:"^.{0,42}$",internal_name:"cart_id"},orderId:{types:["string","number"],internal_name:"order_id"},name:{required:!0,internal_name:"cart_name"},billingCity:{regex:"^.{0,390}$",internal_name:"billing_city"},billingCountry:{regex:"^.{0,85}$",internal_name:"billing_country"},billingPostcode:{regex:"^.{0,10}$",internal_name:"billing_postcode"},billingRegion:{regex:"^.{0,256}$",internal_name:"billing_region"},deliveryType:{regex:"^.{0,42}$",internal_name:"delivery_type"},
paymentType:{regex:"^.{0,42}$",internal_name:"payment_type"},shippingCity:{regex:"^.{0,390}$",internal_name:"shipping_city"},shippingCost:{types:["string","number"],regex:this.REGULAR_EXPRESSIONS.DECIMAL,internal_name:"shipping_cost"},shippingCountry:{regex:"^.{0,85}$",internal_name:"shipping_country"},shippingPostcode:{regex:"^.{0,10}$",internal_name:"shipping_postcode"},shippingRegion:{regex:"^.{0,256}$",internal_name:"shipping_region"},tax:{types:["string","number"],regex:this.REGULAR_EXPRESSIONS.DECIMAL},
totalCartValue:{types:["string","number"],regex:this.REGULAR_EXPRESSIONS.DECIMAL,internal_name:"total_cart_value"},apiEventKey:{}},cartaction:{action:{required:!0,regex:"^add$|^addFailed$|^update$|^remove$"},cartId:{types:["string","number"],internal_name:"cart_id"},cartName:{internal_name:"cart_name"},cartType:{regex:"^cartview$|^checkout$",internal_name:"cart_type"},group:{regex:"^.{0,130}$",internal_name:"product_group"},productId:{types:["string","number"],group:"identificationGroup",regex:"^.{0,130}$",
group_min:1,internal_name:"product_id"},productName:{group:"identificationGroup",regex:"^.{0,130}$",group_min:1,internal_name:"product_name"},productSku:{types:["string","number"],group:"identificationGroup",regex:"^.{0,100}$",group_min:1,internal_name:"product_sku"},quantity:{types:["string","number"],regex:this.REGULAR_EXPRESSIONS.DECIMAL,internal_name:"product_quantity"},unitPrice:{types:["string","number"],regex:this.REGULAR_EXPRESSIONS.DECIMAL,internal_name:"product_unit_price"},uri:{required:!0,
default_value:function(){return document.URL}},apiEventKey:{}},cartitem:{id:{types:["string","number"],group:"cartItemGroup",regex:"^.{0,130}$",group_min:1,internal_name:"product_id"},name:{group:"cartItemGroup",regex:"^.{0,130}$",group_min:1,internal_name:"product_name"},sku:{types:["string","number"],group:"cartItemGroup",regex:"^.{0,100}$",group_min:1,internal_name:"product_sku"},quantity:{types:["string","number"],regex:this.REGULAR_EXPRESSIONS.INTEGER,internal_name:"product_quantity"},unitPrice:{types:["string",
"number"],regex:this.REGULAR_EXPRESSIONS.DECIMAL,internal_name:"product_unit_price"},group:{regex:"^.{0,130}$",internal_name:"product_group"},availabilityMessage:{regex:"^.{0,650}$",internal_name:"availability_message"},shippingMessage:{regex:"^.{0,650}$",internal_name:"shipping_message"},savingsMessage:{regex:"^.{0,650}$",internal_name:"savings_message"}},change:{attempts:{required:!0,default_value:function(){return"1"},internal_name:"form._o.attempts"},uri:{required:!0,default_value:function(){return document.URL}},
id:{required:!0,internal_name:"form._o.id"},name:{internal_name:"form._h.name"}},click:{uri:{},anchorId:{types:["string","number"],internal_name:"anchor_id"},pageTitle:{required:!0,default_value:function(){return document.title},internal_name:"page_title"},title:{required:!1},referrer:{required:!0,default_value:function(){return document.referrer}},anchorHref:{internal_name:"anchor_href"},anchorName:{internal_name:"anchor_name"},elementTagName:{},location:{},onClick:{internal_name:"onclick"},targetInnerText:{},
targetSelectorPath:{}},clickthrough:{uri:{required:!0,default_value:function(){return document.URL}},spotName:{required:!0},spotId:{required:!0,internal_name:"spot_id"},variantId:{internal_name:"variant_id"},creativeId:{required:!0,internal_name:"creative_id"},taskId:{required:!0,internal_name:"task_id"}},contentchange:{uri:{required:!0,default_value:function(){return document.URL}},attributeName:{required:!1,internal_name:"attributename"},newValue:{required:!1,internal_name:"newvalue"},oldValue:{required:!1,
internal_name:"oldvalue"},id:{types:["string","number"],internal_name:"targetid"},name:{internal_name:"targetname"},selector:{required:!0,internal_name:"targetselector"},type:{required:!0,regex:"^attribute$|^childremove$|^childadd$",internal_name:"targettype"}},custom:{uri:{required:!0,default_value:function(){return document.URL}},apiEventKey:{}},document:{altText:{internal_name:"targetInnerText"},id:{internal_name:"anchor_id"},url:{required:!0,internal_name:"anchor_href"},name:{internal_name:"anchor_name"},
selectorPath:{internal_name:"targetSelectorPath"}},identity:{loginId:{required:!0,internal_name:"login_event",regex:".+"},loginEventType:{required:!0,regex:"^email_id$|^login_id$|^customer_id$|^subject_id$|^account_id$|^household_id$",internal_name:"login_event_type"},eventSource:{required:!1,default_value:"webmarketing"}},impression:{eventSource:{required:!1,default_value:"webmarketing"},uri:{required:!0,default_value:function(){return document.URL}},spotName:{required:!0},creativeId:{required:!0,
internal_name:"creative_id"},spotId:{required:!0,internal_name:"spot_id"},taskId:{required:!0,internal_name:"task_id"},variantId:{internal_name:"variant_id"}},impressionViewable:{uri:{required:!0,default_value:function(){return document.URL}},spotName:{required:!0},spotId:{required:!0,internal_name:"spot_id"},variantId:{internal_name:"variant_id"},creativeId:{required:!0,internal_name:"creative_id"},taskId:{required:!0,internal_name:"task_id"}},internalSearch:{searchName:{required:!0},term:{required:!0,
internal_name:"searchTerm"},resultsDisplayed:{regex:this.REGULAR_EXPRESSIONS.INTEGER},resultsDisplayFlag:{required:!0,regex:"^true$|^false$"},fieldId:{internal_name:"searchFieldId"},fieldName:{internal_name:"searchFieldName"},apiEventKey:{}},jsvarchange:{uri:{required:!0,default_value:function(){return document.URL}},name:{required:!0},action:{default_value:"update",regex:"^add$|^update$"},oldValue:{required:!0,internal_name:"oldvalue"},newValue:{required:!0,internal_name:"newvalue"}},load:{uri:{required:!0,
default_value:function(){return document.URL}},pageTitle:{required:!0,default_value:function(){return document.title},internal_name:"page_title"},referrer:{required:!0,default_value:function(){return document.referrer}}},media:{uri:{required:!0,default_value:function(){return document.URL}},id:{required:!0,internal_name:"player_id"},url:{required:!0,regex:"^.{0,260}$",internal_name:"media"},player:{required:!0,regex:"^.{0,30}$",internal_name:"media_player"},position:{required:!0,types:["string","number"],
regex:this.REGULAR_EXPRESSIONS.INTEGER,internal_name:"media_position"},duration:{required:!0,types:["string","number"],regex:this.REGULAR_EXPRESSIONS.DECIMAL,internal_name:"media_duration"},action:{required:!0,regex:"^start$|^stop$|^end$",internal_name:"media_action"}},productView:{id:{group:"identificationGroup",group_min:1,internal_name:"product_id"},name:{group:"identificationGroup",group_min:1,internal_name:"product_name"},sku:{group:"identificationGroup",group_min:1,internal_name:"product_sku"},
quantity:{internal_name:"product_quantity",regex:this.REGULAR_EXPRESSIONS.INTEGER},unitPrice:{internal_name:"product_unit_price",regex:this.REGULAR_EXPRESSIONS.DECIMAL},group:{internal_name:"product_group",regex:"^.{0,130}$"},availabilityMessage:{internal_name:"availability_message",regex:"^.{0,650}$"},shippingMessage:{internal_name:"shipping_message",regex:"^.{0,650}$"},savingsMessage:{internal_name:"savings_message",regex:"^.{0,650}$"},apiEventKey:{}},promotion:{trackingCode:{},creativeName:{internal_name:"creative"},
placementId:{},name:{required:!0,internal_name:"promotionName"},recordType:{required:!0,regex:"display|use"},type:{required:!0,internal_name:"promotionType"},apiEventKey:{}},submit:{attempts:{required:!0,default_value:function(){return"1"},internal_name:"form._o.attempts"},uri:{required:!0,default_value:function(){return document.URL}},referrer:{required:!0,default_value:function(){return document.referrer}},id:{required:!0,internal_name:"form._o.id"},location:{},name:{types:["number","string"],internal_name:"form._h.name"}}};
this.commonFieldHandling=function(a,d,e){var c=e.id||e.name,f=e.value,k="form.f."+c;if("true"===e.obscure){var h="ffobscure."+ ++a.obscureCount;d[h]=k;f=b.encodingService.sha384(f+b.extTenantId)}a.paramMap.set(k,f);null!=e.type&&a.paramMap.set("form.f."+c+"._h.type",e.type);null!=e.alt&&a.paramMap.set("form.f."+c+"._h.alt",e.alt);null!=e.id&&a.paramMap.set("form.f."+c+"._h.id",e.id);null!=e.name&&a.paramMap.set("form.f."+c+"._h.name",e.name);null!=e.changes&&a.paramMap.set("form.f."+c+"._o.changes",
e.changes)};this.obfuscateFields=function(a){var c=a.paramMap.get("obfuscateFields"),e=[];if(null!=c)try{e=JSON.parse(c)}catch(t){console.log("ERROR in field obfuscation")}for(c=0;c<e.length;c++){var g=e[c],f=a.paramMap.get(g);if(null!=f){a.paramMap.set(g,b.encodingService.sha384(f+b.extTenantId));f="ffobscure."+ ++a.obscureCount;var h=a.paramMap.get("eventName");h=b.PARAMS_METADATA[h];var p=void 0;null!=h[g]&&(p=h[g].internal_name);a.paramMap.set(f,null!=p?p:g)}}a.paramMap.delete("obfuscateFields")};
this.encodingService=a}e.prototype.mapTransportNames=function(a){var b=a.paramMap.get("eventName"),c=this.PARAMS_METADATA[b],d={impression:"spot_change",impressionViewable:"impression_viewable",clickthrough:"spot_clicked",identity:"IdentityEvent"},e;for(e in d)b===e&&a.paramMap.set("eventName",d[e]);for(var g in c)(b=c[g].internal_name)&&a.paramMap.has(g)&&(a.paramMap.set(b,a.paramMap.get(g)),a.paramMap.delete(g))};e.prototype.getParamsMetadata=function(){return this.PARAMS_METADATA};e.prototype.cartEventHandling=
function(a,b){b=b.items;if(null!=b){var c;for(c=0;c<b.length;c++){var d=b[c],e=new f.CI360EventObj("cartitem",Date.now()),g;for(g in d)d.hasOwnProperty(g)&&e.paramMap.set(g,d[g]);if("success"===this.validateEvent(e)){d=this.PARAMS_METADATA.cartitem;for(var h in d){var x=d[h].internal_name;x&&e.paramMap.has(h)&&(e.paramMap.set(x,e.paramMap.get(h)),e.paramMap.delete(h))}a.paramMap.set("cartitem."+(c+1),e.toURLEncoded())}}a.paramMap.set("cartitem_count",c)}};e.prototype.changeEventHandling=function(a,
b){var c=b.field;null!=c&&(this.commonFieldHandling(a,b,c),delete b.field)};e.prototype.addFieldsToEvent=function(a,b){for(var c in b)b.hasOwnProperty(c)&&a.paramMap.set(c,b[c])};e.prototype.submitEventHandling=function(a,b){var c=b.fields;if(null!=c){for(var d=0;d<c.length;d++)this.commonFieldHandling(a,b,c[d]);delete b.fields}};e.prototype.resolveDefaultVal=function(a,b){var c={types:["string"],regex:".*",required:!1};return void 0!==a?a:c[b]};e.prototype.addDefaultFields=function(a){var b=this.PARAMS_METADATA[a.paramMap.get("eventName")],
c;for(c in b){var d=b[c];null!=d.default_value&&null==a.paramMap.get(c)&&("function"===typeof d.default_value&&(d.default_value=d.default_value()),a.paramMap.set(c,d.default_value))}};e.prototype.validateEvent=function(a){if(""!==a.paramMap.get("datahub_id")){var b=a.paramMap.get("eventName");if(b){var c=this.PARAMS_METADATA[b];if(null!=c){var d=new Map;for(p in c){var e=c[p];if(this.resolveDefaultVal(e.required,"required")&&"spotName"!==p&&null==a.paramMap.get(p))return this.SPOT_DEP_EVENTS[b]&&
this.SPOT_DEP_EVENT_KEYS[p]?null==a.paramMap.get("spotName")?"required parameter: spotName not provided":"required precondition: getCreatives not executed, or no creative delivered for spotName":"required parameter: "+p+" not provided";var g=e.group;if(null!=g){var f=d.get(g);null==f&&d.set(g,{count:0,min:e.group_min})}}var h=[];a.paramMap.forEach(function(a,c,b){h.push(c)});for(b=0;b<h.length;b++){var p=h[b];g=a.paramMap.get(p);f=c[p];if(null!=f){e=new RegExp(this.resolveDefaultVal(f.regex,"regex"));
if(!e.test(g)&&f.required)return'regular expression: "'+e+'" does not match "'+g+'" for param "'+p+'"';null!=f.group&&(g=f.group,f=d.get(g),f.count++)}}var t=!0,l="";d.forEach(function(a,c){a.count<a.min&&(l+=c+", ",t=!1)});return t?"success":(l=l.slice(0,l.length-2),"groups invalid: "+l)}}else return"eventName parameter not provided";return"validation failed for: "+b}return"Configuration is invalid. Possible unapproved domain."};return e}();f.ParamService=h})($ci360||($ci360={}));
(function(f){var h=function(){function e(){var a=this;this.VID_PREF="_SI_VID_1.";this.SID_PREF="_SI_SID_1.";this.DID_PREF="_SI_DID_1.";this.TAB_PREF="_ciutbid_";this.setExtTenantId=function(b){a.extTenantId=b};this.setSld=function(b){a.sld=b};this.vidName=function(){return a.VID_PREF+a.extTenantId};this.sidName=function(){return a.SID_PREF+a.extTenantId};this.didName=function(){return a.DID_PREF+a.extTenantId};this.setCookieOnSLDs=function(b,c,d){if(null!=c&&c!=a.getCookie(b))if(a.sld&&null!=a.sld){var e=
a.sld.split(","),f;for(f in e)if(a.getCookie(b)!=c)a.setCookie(b,c,d,e[f]);else break}else a.setCookie(b,c,d)};this.setCookie=function(a,c,d,e){var b=";";if(null!=d){var f=new Date;f.setTime(f.getTime()+(0<d?864E5*d:31536E6));b+="expires="+f.toUTCString()}document.cookie=a+"="+c+b+";path=/"+(null==e?"":"; domain="+e)};this.getCookie=function(a){return(a=document.cookie.match("(^|;)\\s*"+a+"\\s*=\\s*([^;]+)"))?a.pop():""};this.setVid=function(b){a.setCookieOnSLDs(a.vidName(),b,0)};this.getVid=function(){return a.getCookie(a.vidName())};
this.setSid=function(b){if(b){var c=(new Date).getTime(),d=a.getSidArray();d=d[0]==b?Math.max(c-Number(d[1]),Number(d[2])):null;a.setCookieOnSLDs(a.sidName(),b+"."+c+"."+(d||0),null)}};this.getSidArray=function(){var b=a.getCookie(a.sidName());return b&&(b=b.split("."),2<b.length)?b:["","0","0"]};this.setDid=function(b){a.setCookieOnSLDs(a.didName(),b,0)};this.getDid=function(){return a.getCookie(a.didName())};this.registerActivity=function(){a.setSid(a.getSidArray()[0])};this.getTabId=function(){var b=
f.sessionStorage.getItem(a.TAB_PREF);b||(b=Math.floor(1E12*Math.random()+1).toString(),f.sessionStorage.setItem(a.TAB_PREF,b));return b}}e.prototype.getCookies=function(){for(var a=document.cookie.split(";"),b={},c=0;c<a.length;c++){var d=a[c].split("="),e=(d[0]+"").trim();b[e]=unescape(d[1])}return b};return e}();f.PersistenceService=h})($ci360||($ci360={}));
(function(f){(function(){var h={sessionStorage:"sessionStorage",localStorage:"localStorage"},e;for(e in h)f[h[e]]=e in window?window[e]:{_data:{},setItem:function(a,b){return this._data[a]=String(b)},getItem:function(a){return this._data.hasOwnProperty(a)?this._data[a]:void 0},removeItem:function(a){return delete this._data[a]},clear:function(){return this._data={}}}})()})($ci360||($ci360={}));
(function(f){var h=function(){function e(a){var b=this;this.spotNamesToIdsMap=new Map;this.tmpSpotNamesToIdsMap=new Map;this.getSpotNamesToIdsMap=function(){return b.spotNamesToIdsMap};this.buildSpotDefUrl=function(a){var c=a.domain||window.location.hostname,e=a.path||window.location.pathname,f="";if(a.params){f=[];for(var h in a.params)f.push(encodeURIComponent(h)+"="+encodeURIComponent(a.params[h]));a=f.join("&");f=encodeURIComponent(a.replace(/[!'()*]/g,function(a){return"%"+a.charCodeAt(0).toString(16).toUpperCase()}))}else f=
window.location.search;return b.isConfigValid()?b.config.sdu+"?domain="+c+"&p="+e+"&params="+f:""};this.getSpotDefsInternal=function(a,d){if(b.isConfigValid()){var c=new XMLHttpRequest;c.onreadystatechange=function(){if(c.readyState===XMLHttpRequest.DONE&&200===c.status){var a=[];c.responseText&&(a=JSON.parse(c.responseText));d(null,a)}else c.readyState===XMLHttpRequest.DONE&&d(Error("Spot definitions could not be retrieved: "+c.statusText),null)};c.open("GET",b.buildSpotDefUrl(a));c.send()}};this.getSpotDefinitions=
function(a,d){b.getSpotDefsInternal(a,function(c,b){var e=new Map;if(!c){for(var f=[],g=0;g<b.length;g++){var h=b[g];if("spotSet"===h.spotType&&(!a.names||a.names&&-1<a.names.indexOf(h.spotName))){var k=0;for(h=h.spotList;k<h.length;k++)f.push(h[k])}}for(g=0;g<b.length;g++)h=b[g],("spot"===h.spotType&&(!a.names||a.names&&-1<a.names.indexOf(h.spotName))||-1<f.indexOf(h.spotId))&&e.set(h.spotName,{id:h.spotId,selector:h.selector,attributes:h.spotAttributes})}d(c,e)})};this.getCreativesUrls=function(a,
d){var c=a.domain||window.location.hostname;b.getSpotDefsInternal(a,function(g,h){if(!g&&b.isConfigValid()){g=b.config.csu.replace("hserver","bserverj");g=g+"/ball/domain="+c;g+="/customerid="+b.configService.getDatahubId();g+="/sessionid="+(a.sid||b.config.sid);g+="/hint=x";for(var k=0,m=[],t=new Map,l=[],q=g,r=[],v=b.getViewId(),C=new Map,w=0;w<h.length;w++){var n=h[w];if("spotSet"===n.spotType&&(!a.names||a.names&&-1<a.names.indexOf(n.spotName))){var y=b.getViewId(),F=0;for(n=n.spotList;F<n.length;F++){var K=
n[F];l.push(K);C.set(K,y)}}else b.tmpSpotNamesToIdsMap.set(n.spotName,{spotId:n.spotId}),C.set(n.spotId,v)}for(w=0;w<h.length;w++)if(n=h[w],"spot"===n.spotType&&(!a.names||a.names&&-1<a.names.indexOf(n.spotName))||-1<l.indexOf(n.spotId)){q.length>e.MAX_URL_SIZE&&(t.set(q,m),r.push(q),k=0,m=[],q=g);m.push(""+n.spotName);y="";v=void 0;a.attributes&&(v=a.attributes[n.spotName]);if(v)for(var z in v)"product_id"===z||"product_sku"===z?(z+="_key",y+=z+"="+v[z]+".trim()/"):null!=v[z]&&b.containsAttribute(n.spotAttributes,
z)&&(y+=z+"="+f.Base64.encode(v[z].trim()).replace(/=/g,"")+"/");q+="/b"+ ++k+"/spot_id="+n.spotId+"/"+y+"viewid="+C.get(n.spotId)}m.length&&(t.set(q,m),r.push(q));d(null,r,t)}else d(g,null,null)})};this.configService=a}e.prototype.init=function(a){this.config=this.configService.getConfig();a()};e.prototype.isConfigValid=function(){return this.config&&this.config.sdu?!0:!1};e.prototype.handleCreativesUrlResponse=function(a,b,c){return function(){if(a.readyState===XMLHttpRequest.DONE&&200===a.status){var d=
[];if(a.responseText)try{d=JSON.parse(a.responseText)}catch(k){c(Error("Creatives response could not be parsed: "+k),b,null)}c(null,b,d)}else a.readyState===XMLHttpRequest.DONE&&c(Error("Creatives could not be retrieved: "+a.statusText),b,null)}};e.prototype.getCreatives=function(a,b){var c=this;this.getCreativesUrls(a,function(a,e,f){if(a)b(a,null);else{var d=new Map,g=0,h=!0;a=function(a,e,k){if(!a&&h){g++;var l=a=0;e=f.get(e);for(var m=0;m<k.length;m++){var p=k[m],q=e[a++],r=c.parseCreative(p);
d.set(q,r);l+=c.addSpotNameToIds(q,p)}g===f.size&&(c.deleteSpotNamesToIds(l),b(null,d))}else h&&(h=!1,b(a,null))};if(f.size)for(var k=0;k<e.length;k++){var l=e[k],q=new XMLHttpRequest;q.onreadystatechange=c.handleCreativesUrlResponse(q,l,a);q.open("GET",l);q.send()}else b(null,new Map)}})};e.prototype.getPersonalizedCreative=function(a,b){var c=this;a.delay=a.delay||e.DELAY;a.retries=null!=a.retries?a.retries:e.RETRIES;this.getCreatives(a,function(d,e){d?b(d,null):1===e.size?e.forEach(function(d){d.creativeId?
b(null,d):1>--a.retries?b(null,null):setTimeout(function(a,b){c.getPersonalizedCreative(a,b)},a.delay,a,b)}):0===e.size?b(Error("No creative found"),null):1<e.size&&b(Error("More than one creative found"),null)})};e.prototype.addSpotNameToIds=function(a,b){var c=0;(b=this.parseCreative(b))&&b.creativeId&&b.taskId&&(c++,a=this.tmpSpotNamesToIdsMap.get(a))&&(a.creativeId=b.creativeId,a.taskId=b.taskId,a.variantId=b.variantId);return c};e.prototype.parseCreative=function(a){var b={content:a.replace(/<data .*<\/data>/,
"").replace(/<data .*?\/>/,"")},c=a.match(/data-creativeID="([A-Za-z0-9\-]+)"/);c&&c[1]&&(b.creativeId=c[1],(c=a.match(/data-taskID="([A-Za-z0-9\-]+)"/))&&c[1]&&(b.taskId=c[1],(a=a.match(/data-variant_id="([A-Za-z0-9\-]+)"/))&&a[1]&&(b.variantId=a[1])));return b};e.prototype.deleteSpotNamesToIds=function(a){var b=this;a=this.spotNamesToIdsMap.size-e.MAX_SPOT_NAMES_TO_CACHE+a;0<a&&Array.from(this.spotNamesToIdsMap.keys()).slice(0,a).forEach(function(a){b.spotNamesToIdsMap.delete(a)});this.tmpSpotNamesToIdsMap.forEach(function(a,
d){a.creativeId&&b.spotNamesToIdsMap.set(d,a)});this.tmpSpotNamesToIdsMap.clear()};e.prototype.decorateEvent=function(a){var b=a.paramMap.get("eventName");if("clickthrough"===b||"impression"===b||"impressionViewable"===b)if(b=this.spotNamesToIdsMap.get(a.paramMap.get("spotName")))a.paramMap.set("spotId",b.spotId),a.paramMap.set("taskId",b.taskId),a.paramMap.set("creativeId",b.creativeId),b.variantId&&a.paramMap.set("variantId",b.variantId),a.paramMap.delete("spotName")};e.prototype.getViewId=function(){return Math.floor(1E12*
Math.random()+1).toString()};e.prototype.containsAttribute=function(a,b){for(var c=0;c<a.length;c++)if(a[c].name===b)return!0};e.MAX_URL_SIZE=1800;e.MAX_SPOT_NAMES_TO_CACHE=1E4;e.DELAY=1E3;e.RETRIES=30;return e}();f.SpotService=h})($ci360||($ci360={}));
(function(f){var h=function(){function e(){var a=this;this.extractParam=function(b,c){return c&&b&&(b=a.getUriInfoGeneric(c).searchObj[b])?b.replace(/\+/g," "):null};this.getJsVarValueSafe=function(a){var b=window;a.split(".").forEach(function(a){b=b&&b[a]});return b&&b.toString()||null}}e.prototype.isSelectorValid=function(a){var b=document.createElement("br");a:{try{b.querySelector(a)}catch(c){a=!1;break a}a=!0}return a};e.prototype.getUriInfoGeneric=function(a){var b=document.createElement("a");
b.href=a;a=b.search.substring(1);for(var c=a.split("&"),d={},e=0;e<c.length;e++){var f=c[e].split("=");d[decodeURIComponent(f[0])]=decodeURIComponent(f[1]||"")}return{protocol:b.protocol.replace(":",""),host:b.hostname,port:b.port,path:("/"!==b.pathname.charAt(0)?"/":"")+b.pathname,search:a,searchObj:d}};e.prototype.getUriInfo=function(){return this.getUriInfoGeneric(document.URL)};e.prototype.getMeta=function(a){for(var b=document.getElementsByTagName("meta"),c=b.length,d=0;d<c;d++)if(b[d].getAttribute("name")===
a)return b[d].getAttribute("content");return""};e.prototype.getMetas=function(){for(var a=document.getElementsByTagName("meta"),b={},c=a.length,d=0;d<c;d++){var e=a[d],f=e.getAttribute("name");f&&(b[f]=e.getAttribute("content"))}return b};e.prototype.getDataAttributes=function(a){a=a.dataset;var b={},c;for(c in a)b[c]=a[c];return b};e.prototype.nextChar=function(a,b,c){var d=a.indexOf(b);a=a.indexOf(c);return-1===d&&-1==a?"":-1===d?c:-1===a?b:d<a?b:c};e.prototype.tokenizeObjectString=function(a){for(var b=
[];0<a.length;){var c=a.indexOf("."),d=a.indexOf("[");if(0!==c&&0!==d){var e=this.nextChar(a,".","[");"."===e?(b.push(a.substring(0,c)),a=a.slice(c)):"["===e?(b.push(a.substring(0,d)),a=a.slice(d)):(b.push(a),a="")}else 0===c?(a=a.slice(1),e=this.nextChar(a,".","["),""!==e?(c=a.indexOf(e),b.push(a.substring(0,c)),a=a.slice(c)):(b.push(a),a="")):0===d?(c=d+1,d=a.charAt(c),d=a.slice(c+1).indexOf(d)+c+1,e=d+1,b.push(a.substring(c+1,d)),a=a.slice(e+1)):a=""}return b};e.prototype.getVariableFromObjectString=
function(a){for(var b=a.length,c=0,d=window;null!=d&&c<b;)d=d[a[c++]];return c&&c===b?d:void 0};e.prototype.debounce=function(a,b,c){function d(b){var c=p,d=t;p=t=void 0;v=b;return l=a.apply(d,c)}function e(a){var c=a-r;a-=v;return void 0===r||c>=b||0>c||w&&a>=y}function f(){var a=Date.now();if(e(a))return h(a);var c=a-v;a=b-(a-r);q=setTimeout(f,w?Math.min(a,y-c):a)}function h(a){q=void 0;if(n&&p)return d(a);p=t=void 0;return l}function x(){for(var a=[],c=0;c<arguments.length;c++)a[c]=arguments[c];
c=Date.now();var g=e(c);p=a;t=this;r=c;if(g){if(void 0===q)return v=a=r,q=setTimeout(f,b),C?d(a):l;if(w)return q=setTimeout(f,b),d(r)}void 0===q&&(q=setTimeout(f,b));return l}var p,t,l,q,r,v=0,C=!1,w=!1,n=!0;if("function"!==typeof a)throw new TypeError("Expected a function");b=+b||0;if(c){C=!!c.leading;var y=(w="maxWait"in c)?Math.max(+c.maxWait||0,b):y;n="trailing"in c?!!c.trailing:n}x.flush=function(){return void 0===q?l:h(Date.now())};x.pending=function(){return void 0!==q};return x};e.prototype.throttle=
function(a,b,c){var d=!0,e=!0;if("function"!==typeof a)throw new TypeError("Expected a function");c&&(d="leading"in c?!!c.leading:d,e="trailing"in c?!!c.trailing:e);return this.debounce(a,b,{leading:d,trailing:e,maxWait:b})};e.prototype.filterElemsBySelector=function(a,b){for(var c=[],d=0;d<b.length;d++){a instanceof HTMLElement&&a.matches(b[d])&&c.concat(a);for(var e=a.querySelectorAll(b[d]),f=e.length,h=0;h<f;h++)c=c.concat(e[h])}return c};e.prototype.urlEncodedToJSONObject=function(a){var b={};
a=("?"===a[0]?a.substr(1):a).split("&");for(var c=0;c<a.length;c++){var d=a[c].split("=");b[decodeURIComponent(d[0])]=decodeURIComponent(d[1]||"")}return b};e.prototype.jsonObjectToUrlEncoded=function(a){var b="",c;for(c in a)b+=encodeURIComponent(c)+"="+encodeURIComponent(a[c])+"&";return b.slice(0,b.length-1)};return e}();f.Util=h})($ci360||($ci360={}));
(function(f){var h=new f.Util,e=new f.Bootstrap,a=new f.PersistenceService,b=new f.LocalQueue("ciq2_","sessionStorage");b=new f.NetworkService(b,a);var c=new f.EncodingService;c=new f.ParamService(c);h=new f.ConfigService(a,b,c,h);var d=new f.SpotService(h);a=new f.EventService(h,a,b,c,d);e.require(h,d);e.createApi(h,c,a,d);h.setEnvironmentAttributes(e.getEnvironmentAttributes());e.setLazyInit(f.lazyInit);e.initialize()})($ci360||($ci360={}));
